[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "text-to-tensor-api"
version = "0.1.0"
description = "API to transform text to tensor"
authors = [
    { name = "Nikita Navalikhin", email = "noviiden@gmail.com" },
]
dependencies = [
    "fastapi[standard]>=0.100.0",
    "uvicorn>=0.23.2",
    "torch>=2.0.0",
    "transformers>=4.33.2",
    "requests>=2.32.3",
    "pdfreader>=0.1.15",
    "pypdf2>=3.0.1",
    "pyvespa>=0.55.0",
    "vespacli>=8.497.38",
]
